### ISSUE TITLE
SwiftPackage not working

### ISSUE THREAD

**Issue by ghost** [fastred/DeallocationChecker#14]
Hello,
I think your project is very interesting and I just want to give it a try. Unfortunately I get it in the SWP not imported. I always get the following error message:

The package dependency graph can not be resolved; unable find any available tag for the following requirements:

https://github.com/fastred/DeallocationChecker/ — 2.0.1..<3.0.0

**Comment by fastred** [comment]
Thanks for reporting this issue. It's fixed in `3.0.1` release.
