### ISSUE TITLE
UISearchController root?

### ISSUE THREAD

**Issue by bunnyhero** [fastred/DeallocationChecker#16]
DeallocationChecker is reporting a leak for me when the view controller I've assigned as `searchResultsController` in a `UISearchController` is dismissed. If I understand everything correctly, I don't think this should count as a leak, similar to how `UITabBarController` is handled, although I'm not 100% sure.

**Comment by fastred** [comment]
I recall seeing that in the past. It could be a real leak caused by UIKit: https://github.com/larryryu/SearchControllerBug

**Comment by bunnyhero** [comment]
That's interesting. I did a test using a fork of DeallocationChecker, and DeallocationChecker reported a leak, despite the Memory Graph Debugger not showing any instances of the supposedly leaked view controller

**Comment by fastred** [comment]
Interesting. That definitely shouldn’t happen. I could take a look if you’d be able to post a sample project.

**Comment by bunnyhero** [comment]
I checked again and I made a mistake in my test. You are correct!

**Comment by fastred** [comment]
Cool! Thanks for letting me know.
