### ISSUE TITLE
Doesn't work when imported in an Objective-c project?

### ISSUE THREAD

**Issue by sarperdag** [fastred/DeallocationChecker#4]
Trying to use this in an objC project, but it never fires an error even if I'm 100% sure the VC is not being deallocated...

**Comment by fastred** [comment]
Can you try putting a breakpoint on [the line with assertion](https://github.com/fastred/DeallocationChecker/blob/master/Sources/DeallocationChecker.swift#L33) to see if it's executed?

**Comment by sarperdag** [comment]
Tried that but the breakpoint gets hit at the end of the function. Can't even debug it line by line and see what's going on... Don't have much experience with using Swift code in objective-c projects, maybe Xcode is showing smt non-sense?

**Comment by fastred** [comment]
I think this is caused by `#if DEBUG` being false and skipping the whole implementation. Can you see if adding this in your `Podfile` helps?

```ruby
# Enable DEBUG flag in Swift for DeallocationChecker
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'DeallocationChecker'
            target.build_configurations.each do |config|
                if config.name == 'Debug'
                    config.build_settings['OTHER_SWIFT_FLAGS'] = '-DDEBUG'
                end
            end
        end
    end
end
```

**Comment by sarperdag** [comment]
Still not working. This time it's another error:

> Pods/DeallocationChecker/Sources/DeallocationChecker.swift:45:17: Method 'objc_dch_checkDeallocation(delay:)' with Objective-C selector 'dch_checkDeallocationAfterDelay:' conflicts with method 'dch_checkDeallocation(afterDelay:)' with the same Objective-C selector

**Comment by fastred** [comment]
@sarperdag Thanks for reporting!

I just pushed DeallocationChecker 2.0.1 which should fix this issue. No need for that `post_install` phase I mentioned before too.

**Comment by sarperdag** [comment]
OK updated to 2.0.1 but here's a new error :)

> Implicit declaration of function 'dch_checkDeallocation' is invalid in C99

I'm importing the library using:

> #import "DeallocationChecker-Swift.h"

**Comment by fastred** [comment]
Can you try importing using?

```
@import DeallocationChecker;
```

**Comment by sarperdag** [comment]
Already tried that, not working :)

--
Sarp Erdag

**Comment by fastred** [comment]
I think I know what's wrong. It's a method on `UIViewController`, so from Objective-C you have to call it this way:

```obj-c
[self dch_checkDeallocation];
```

Full example:


```obj-c
- (void)viewDidDisappear:(BOOL)animated
{
    [super viewDidDisappear:animated];

    [self dch_checkDeallocation];
}
```

**Comment by sarperdag** [comment]
yup, that's the reason. Seems to be working fine now. Thanks for the support!

**Comment by fastred** [comment]
Great to finally get this working under Obj-C! 😃
