### ISSUE TITLE
DeallocationChecker.swift:45:17: Method 'objc_dch_checkDeallocation(delay:)' with Objective-C selector 'dch_checkDeallocationAfterDelay:' conflicts with method 'dch_checkDeallocation(afterDelay:)' with the same Objective-C selector

### ISSUE THREAD

**Issue by nebiros** [fastred/DeallocationChecker#7]
Got this error with the latest version:

```
Pods/DeallocationChecker/Sources/DeallocationChecker.swift:45:17: Method 'objc_dch_checkDeallocation(delay:)' with Objective-C selector 'dch_checkDeallocationAfterDelay:' conflicts with method 'dch_checkDeallocation(afterDelay:)' with the same Objective-C selector
```

I'm at swift 3.2, Xcode 9.0.1

**Comment by fastred** [comment]
Version 2.0 of DeallocationChecker supports only Swift 4. [AFAIK](https://github.com/CocoaPods/CocoaPods/issues/6791) it's not possible to specify the Swift version in `.podspec` file, so CocoaPods tries to build DeallocationChecker with the Swift version your project uses.

There are two possible solutions to this problem:
1. Use version 1.0.2 of DeallocationChecker (this is fine if your project is in Swift).
2. Add a post install phase to your `Podfile` instructing CocoaPods to use Swift 4.0 for DeallocationChecker:

    ```ruby
    post_install do |installer|
        installer.pods_project.targets.each do |target|
            if ['DeallocationChecker', 'AnotherSwift4OnlyLibrary'].include? target.name
                target.build_configurations.each do |config|
                    config.build_settings['SWIFT_VERSION'] = '4.0'
                end
            end
        end
    end
    ```

**Comment by nebiros** [comment]
@fastred Awesome, worked 👌
