### ISSUE TITLE
Optimize for Swift4 

### ISSUE THREAD

**Issue by sarperdag** [fastred/DeallocationChecker#8]
Getting this warning when building with the latest version of Xcode.

> The use of Swift 3 @objc inference in Swift 4 mode is deprecated. Please address deprecated @objc inference warnings, test your code with “Use of deprecated Swift 3 @objc inference” logging enabled, and then disable inference by changing the "Swift 3 @objc Inference" build setting to "Default" for the "DeallocationChecker" target.

**Comment by fastred** [comment]
Did it start showing when you migrated your project to Swift 4?

DeallocationChecker should build without warnings [when `Swift 3 @objc Inference` setting is set to `Default`](https://stackoverflow.com/a/44380886/1990236) (which is a default for new projects). AFAIK CocoaPods uses settings from your project settings, so it may have different value for `DeallocationChecker` target.

The most correct way of fixing this error is migrating to the new `@objc` inference mode. You can temporarily hide warnings using [`inhibit_warnings` flag](https://guides.cocoapods.org/syntax/podfile.html#inhibit_all_warnings_bang).

**Comment by fastred** [comment]
Closing, as this should have been fixed already.
